version: "3.9"
services:
  blogapp:
    container_name: BlogAppContainer
    image: blogappimage
    build: .
    volumes:
      - .:/blogapp:ro
    ports:
      - 8000:8000
    depends_on:
      - db
  db:
    image: postgres:16
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - 5435:5432
    environment:
      - POSTGRES_DB=BlogDB
      - POSTGRES_USER=dragonuser
      - POSTGRES_PASSWORD=Dragon1234Fire

volumes:
  postgres_data: