version: "3.9"
services:
  blogapp:
    container_name: BlogAppContainer
    image: blogappimage
    command: ["sh", "./start.sh"]
    build: .
    volumes:
      - .:/blogapp
    ports:
      - 8000:8000
    depends_on:
      - db
  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=blogdatabase
      - POSTGRES_USER=dragonuser
      - POSTGRES_PASSWORD=Dragon1234Fire

volumes:
  postgres_data:
