# Generated by Django 4.2.5 on 2023-09-25 14:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src_users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 25, 14, 40, 37, 616718)),
        ),
        migrations.AddField(
            model_name='user',
            name='updated',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 25, 14, 40, 37, 616728)),
        ),
    ]
