# Generated by Django 4.2.1 on 2023-10-03 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0004_category_tag_blog_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='name',
            field=models.CharField(default='Technology', max_length=150),
        ),
    ]
