<<<<<<< HEAD
# Generated by Django 4.2.1 on 2023-10-03 11:48
=======
# Generated by Django 4.2.1 on 2023-10-03 10:37
>>>>>>> 0e5e08632bdc5f3ad11f113925de0cc4cc2b93f0

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0005_category_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=150),
        ),
    ]
