# Generated by Django 4.2.1 on 2023-10-08 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0007_userprofile_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='user_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
