# Generated by Django 4.2.1 on 2023-10-03 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0008_remove_blog_tags_blog_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='tags',
            field=models.ManyToManyField(related_name='tag_posts', to='myApp.tag'),
        ),
    ]
