# Generated by Django 4.2.1 on 2023-10-03 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0009_blog_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='category',
        ),
        migrations.AddField(
            model_name='tag',
            name='category',
            field=models.ManyToManyField(related_name='tags', to='myApp.category'),
        ),
    ]
