# Generated by Django 4.2.1 on 2023-10-04 05:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0011_alter_userprofile_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='myApp.company'),
        ),
    ]
