# Generated by Django 4.2.1 on 2023-10-10 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0014_company_description_company_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='joinrequest',
            name='fromTo',
            field=models.CharField(choices=[('WriterToCompany', 'WtoC'), ('CompanyToWriter', 'CtoW')], default='CtoW', max_length=20),
        ),
    ]
