# Generated by Django 4.2.1 on 2023-10-12 07:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myApp', '0015_joinrequest_fromto'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='downVote',
            field=models.ManyToManyField(blank=True, related_name='downVotes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='comment',
            name='upVote',
            field=models.ManyToManyField(blank=True, related_name='upVotes', to=settings.AUTH_USER_MODEL),
        ),
    ]
