# Generated by Django 4.2.1 on 2023-10-12 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0016_alter_userprofile_user'),
        ('myApp', '0016_comment_downvote_comment_upvote'),
    ]

    operations = [
    ]
